Find by istex
Inist-CNRS/node-istex pull request #3
Opened 2016-09-20 10:29 UTC by kerphi

2016-09-20 10:30 UTC, kerphi commented
@nojhamster @pseudom a vous de jouer pour la code review et pour merger ensuite

2016-09-20 11:50 UTC, nojhamster commented on index.js
> +    url += options.extraQueryString;
Using the `qs` option may be cleaner and less likely to have side effects. (I believe request uses the `qs` module)

2016-09-20 11:52 UTC, nojhamster commented on test/findByIstexId.js
> +var expect      = require('chai').expect;
This spacing should be fixed.

2016-09-20 11:54 UTC, nojhamster requested changes
Nice, however I would request some minor changes :)

2016-09-21 13:02 UTC, kerphi commented
C'est mieux @nojhamster ?

2016-09-21 13:45 UTC, nojhamster commented on index.js
> +  url = basePath + '?' + qs.stringify(Object.assign(qs.parse(queryString), qs.parse(options.extraQueryString)));
Ne serait-il pas plus simple d'utiliser directement l'option `qs` de request ? Sachant qu'il gère la fusion si jamais l'url contient déjà une querystring. (l'objet `qs` ayant la priorité)

2016-09-21 13:47 UTC, nojhamster reviewed
Je m'interroge sur la gestion de la querystring, je pensais plutôt à l'option `qs` de request et non au module `qs`.

2016-09-21 14:28 UTC, kerphi commented on index.js
> +  url = basePath + '?' + qs.stringify(Object.assign(qs.parse(queryString), qs.parse(options.extraQueryString)));
Je ne connais pas l'option qs de request, je vais regarder.

2016-09-21 14:59 UTC, kerphi commented
Hé voila c'est en effet bien plus simple, qu'en penses tu ?

2016-09-21 15:04 UTC, nojhamster approved these changes
ça me paraît bien, il est temps de merger tout ça :)

2016-09-21 15:05 UTC, merged